Repository prgrms-be-devcourse/java-library-management, pull requests merged in 2023-10, with the labels that each got.

#5 [5기 - 이경민] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/library_management/App.java
  src/main/java/com/programmers/library_management/business/CommandType.java
  src/main/java/com/programmers/library_management/business/LibraryManagement.java
  src/main/java/com/programmers/library_management/domain/Book.java
  src/main/java/com/programmers/library_management/domain/StatusType.java
  src/main/java/com/programmers/library_management/exception/CBookAlreadyExistException.java
  src/main/java/com/programmers/library_management/exception/CBookAlreadyLostException.java
  src/main/java/com/programmers/library_management/exception/CBookAlreadyRantedException.java
  src/main/java/com/programmers/library_management/exception/CBookAlreadyReturnedException.java
  src/main/java/com/programmers/library_management/exception/CBookIdNotExistException.java
  src/main/java/com/programmers/library_management/exception/CBookInOrganizeException.java
  src/main/java/com/programmers/library_management/repository/BookRepository.java
  src/main/java/com/programmers/library_management/repository/ProductBookRepository.java
  src/main/java/com/programmers/library_management/repository/TestBookRepository.java
  src/main/java/com/programmers/library_management/service/LibraryManagementService.java
  src/main/java/com/programmers/library_management/utils/ConsoleIOManager.java
  src/main/java/com/programmers/library_management/utils/CsvFileManager.java
  src/main/java/com/programmers/library_management/utils/UpdateScheduler.java
  src/test/java/com/programmers/library_management/service/ProductLibraryManagementServiceTest.java
  src/test/java/com/programmers/library_management/service/TestLibraryManagementServiceTest.java
  src/test/java/com/programmers/library_management/utils/CsvFileManagerTest.java
Labels: Team-Hoon, 🔥 매운맛

#16 [5기 - 김경훈] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Application.java
  src/main/java/ProgramRunner.java
  src/main/java/config/Appconfig.java
  src/main/java/controller/BookController.java
  src/main/java/domain/Book.java
  src/main/java/domain/BookStatusType.java
  src/main/java/dto/CreateBookRequestDTO.java
  src/main/java/dto/SelectRequestDTO.java
  src/main/java/repository/MemoryRepository.java
  src/main/java/repository/Repository.java
  src/main/java/repository/TestRepository.java
  src/main/java/service/BookService.java
  src/main/java/view/ConsoleView.java
  src/main/java/view/View.java
  src/main/resources/도서목록.csv
  src/test/java/service/BookServiceTest.java
Labels: Team-Hoon, 🔥 매운맛

#11 [5기 - 이유정] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/librarymanagement/LibraryManagementApplication.java
  src/main/java/com/programmers/librarymanagement/application/LibraryManagementService.java
  src/main/java/com/programmers/librarymanagement/domain/Book.java
  src/main/java/com/programmers/librarymanagement/domain/Status.java
  src/main/java/com/programmers/librarymanagement/dto/BookRequestDto.java
  src/main/java/com/programmers/librarymanagement/exception/BookAlreadyLostException.java
  src/main/java/com/programmers/librarymanagement/exception/BookAlreadyRentException.java
  src/main/java/com/programmers/librarymanagement/exception/BookAlreadyReturnException.java
  src/main/java/com/programmers/librarymanagement/exception/BookArrangeException.java
  src/main/java/com/programmers/librarymanagement/exception/BookLostException.java
  src/main/java/com/programmers/librarymanagement/exception/BookNotFoundException.java
  src/main/java/com/programmers/librarymanagement/presentation/LibraryManagementController.java
  src/main/java/com/programmers/librarymanagement/repository/BookRepository.java
  src/main/java/com/programmers/librarymanagement/repository/NormalBookRepository.java
  src/main/java/com/programmers/librarymanagement/repository/TestBookRepository.java
  src/main/java/com/programmers/librarymanagement/utils/ConsoleIo.java
  src/main/java/com/programmers/librarymanagement/utils/CsvFileIo.java
  src/main/resources/data.csv
  src/test/java/com/programmers/librarymanagement/NormalManagementServiceTest.java
  src/test/java/com/programmers/librarymanagement/TestManagementServiceTest.java
Labels: 🔥 매운맛, Team-BingBong

#13 [5기 - 홍지인] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/dev/course/LibraryApplication.java
  src/main/java/dev/course/config/AppConfig.java
  src/main/java/dev/course/config/BookRepositoryConfig.java
  src/main/java/dev/course/config/LibraryConfig.java
  src/main/java/dev/course/controller/BookController.java
  src/main/java/dev/course/domain/AppConstants.java
  src/main/java/dev/course/domain/Book.java
  src/main/java/dev/course/domain/BookState.java
  src/main/java/dev/course/exception/ConsoleIOFailureException.java
  src/main/java/dev/course/exception/FileIOFailureException.java
  src/main/java/dev/course/exception/FuncFailureException.java
  src/main/java/dev/course/exception/MaxRetryFailureException.java
  src/main/java/dev/course/manager/ConsoleManager.java
  src/main/java/dev/course/manager/JSONFileManager.java
  src/main/java/dev/course/repository/BookRepository.java
  src/main/java/dev/course/repository/GeneralBookRepository.java
  src/main/java/dev/course/repository/TestBookRepository.java
  src/main/java/dev/course/service/LibraryManagement.java
  src/main/java/dev/course/util/BookSerializer.java
  src/main/resources/Book.json
  src/test/java/LibraryAppFeatureTest.java
  src/test/resources/TestBook.json
Labels: 🔥 매운맛, Team-BingBong

#18 [5기 - 조인수] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  setting.gradle
  src/main/java/LibraryApplication.java
  src/main/java/common/InitApplication.java
  src/main/java/common/Util.java
  src/main/java/domain/Book.java
  src/main/java/domain/BookDisplayField.java
  src/main/java/domain/BookProcess.java
  src/main/java/domain/BookState.java
  src/main/java/exception/BookNumberAlreadyExistException.java
  src/main/java/exception/EntityNotFoundException.java
  src/main/java/manage/TotalManager.java
  src/main/java/manage/book/BookListManager.java
  src/main/java/manage/book/BookManager.java
  src/main/java/manage/file/BookFileManager.java
  src/main/java/manage/file/CsvBookFileManager.java
  src/main/java/manage/file/TestBookFileManager.java
  src/test/java/manage/book/BookListManagerTest.java
  src/test/java/manage/file/CsvBookFileManagerTest.java
  src/test/resources/temp.csv
Labels: 🔥 매운맛, Team-BingBong

#25 [5기 - 송인재] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/LibrarianApplication.java
  src/main/java/com/programmers/app/Librarian.java
  src/main/java/com/programmers/app/book/controller/BookController.java
  src/main/java/com/programmers/app/book/controller/BookControllerImpl.java
  src/main/java/com/programmers/app/book/domain/Book.java
  src/main/java/com/programmers/app/book/domain/BookStatus.java
  src/main/java/com/programmers/app/book/dto/BookJSON.java
  src/main/java/com/programmers/app/book/dto/BookRequest.java
  src/main/java/com/programmers/app/book/repository/BookRepository.java
  src/main/java/com/programmers/app/book/repository/NormalBookRepository.java
  src/main/java/com/programmers/app/book/repository/TestBookRepository.java
  src/main/java/com/programmers/app/book/service/BookService.java
  src/main/java/com/programmers/app/config/AppConfig.java
  src/main/java/com/programmers/app/config/InitialConfig.java
  src/main/java/com/programmers/app/console/CommunicationAgent.java
  src/main/java/com/programmers/app/console/ConsoleReader.java
  src/main/java/com/programmers/app/exception/ActionNotAllowedException.java
  src/main/java/com/programmers/app/exception/BookNotFoundException.java
  src/main/java/com/programmers/app/exception/InvalidInputException.java
  src/main/java/com/programmers/app/exception/messages/ExceptionMessages.java
  src/main/java/com/programmers/app/file/BookFileManager.java
  src/main/java/com/programmers/app/file/FileManager.java
  src/main/java/com/programmers/app/menu/Menu.java
  src/main/java/com/programmers/app/menu/MenuExecutor.java
  src/main/java/com/programmers/app/menu/MenuSelector.java
  src/main/java/com/programmers/app/mode/Mode.java
  src/main/java/com/programmers/app/mode/ModeSelector.java
  src/main/resources/books.json
  src/test/java/com/programmers/app/LibrarianTest.java
  src/test/resources/booksTest.json
Labels: 🔥 매운맛, Team-BingBong

#30 [5기 - 김현우] 1~2주차 과제: 도서 관리 어플리케이션 코드 리뷰 요청드립니다!
  .gitignore
  README.md
  build.gradle
  diagram.png
  settings.gradle
  src/main/java/com/dev_course/Application.java
  src/main/java/com/dev_course/book/Book.java
  src/main/java/com/dev_course/book/BookManager.java
  src/main/java/com/dev_course/book/BookState.java
  src/main/java/com/dev_course/data_module/DataManager.java
  src/main/java/com/dev_course/data_module/EmptyDataManager.java
  src/main/java/com/dev_course/data_module/JSONDataManager.java
  src/main/java/com/dev_course/io_module/ConsoleBufferedReader.java
  src/main/java/com/dev_course/io_module/ConsoleSystemWriter.java
  src/main/java/com/dev_course/io_module/EmptyInputException.java
  src/main/java/com/dev_course/io_module/Reader.java
  src/main/java/com/dev_course/io_module/Writer.java
  src/main/java/com/dev_course/library/LibraryMessage.java
  src/main/java/com/dev_course/library/LibraryService.java
  src/main/java/com/dev_course/library/LibrarySystem.java
  src/main/java/com/dev_course/library/ModeFactory.java
  src/main/resources/sample_library_data.json
  src/test/java/com/dev_course/book/BookManagerTest.java
  src/test/java/com/dev_course/library/LibraryServiceTest.java
Labels: 🔥 매운맛, Team-BingBong

#21 [5기 - 권효승] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/library/LibraryApplication.java
  src/main/java/library/controller/BookController.java
  src/main/java/library/domain/Book.java
  src/main/java/library/domain/BookStatus.java
  src/main/java/library/dto/BookFindResponse.java
  src/main/java/library/dto/BookSaveRequest.java
  src/main/java/library/exception/BookErrorMessage.java
  src/main/java/library/exception/BookException.java
  src/main/java/library/exception/FileErrorMessage.java
  src/main/java/library/exception/FileException.java
  src/main/java/library/exception/InputErrorMessage.java
  src/main/java/library/exception/InputException.java
  src/main/java/library/repository/BookRepository.java
  src/main/java/library/repository/FileBookRepository.java
  src/main/java/library/repository/InMemoryBookRepository.java
  src/main/java/library/service/BookService.java
  src/main/java/library/util/file/CsvFileHandler.java
  src/main/java/library/view/ConsoleEngine.java
  src/main/java/library/view/Mode.java
  src/main/java/library/view/console/ConsoleIOHandler.java
  src/main/java/library/view/console/in/ConsoleInput.java
  src/main/java/library/view/console/in/ScannerInput.java
  src/main/java/library/view/console/out/ConsoleOutput.java
  src/main/java/library/view/console/out/PrintStreamOutput.java
  src/main/java/library/view/constant/InputMessage.java
  src/main/java/library/view/function/BookFunction.java
  src/main/java/library/view/function/BookFunctionHandler.java
  src/main/resources/books.csv
  src/test/java/library/domain/BookTest.java
  src/test/java/library/repository/FileBookRepositoryTest.java
  src/test/java/library/repository/InMemoryBookRepositoryTest.java
  src/test/java/library/service/BookServiceTest.java
  src/test/java/library/util/file/CsvFileHandlerTest.java
  src/test/java/library/view/ModeTest.java
  src/test/java/library/view/function/BookFunctionTest.java
  src/test/resources/books.csv
Labels: Team-R, 🔥 매운맛

#26 [5기 - 이수진] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Main.java
  src/main/java/app/library/management/App.java
  src/main/java/app/library/management/config/Configuration.java
  src/main/java/app/library/management/config/factory/BookRepositoryFactory.java
  src/main/java/app/library/management/config/util/PropertiesUtil.java
  src/main/java/app/library/management/core/controller/BookController.java
  src/main/java/app/library/management/core/domain/Book.java
  src/main/java/app/library/management/core/domain/BookStatus.java
  src/main/java/app/library/management/core/domain/util/BookStatusManager.java
  src/main/java/app/library/management/core/domain/util/SchedulerManager.java
  src/main/java/app/library/management/core/repository/BookRepository.java
  src/main/java/app/library/management/core/repository/file/Book.json
  src/main/java/app/library/management/core/repository/file/BookVO.java
  src/main/java/app/library/management/core/repository/file/FileStorage.java
  src/main/java/app/library/management/core/repository/file/FileStorageAdaptor.java
  src/main/java/app/library/management/core/repository/file/Mapper.java
  src/main/java/app/library/management/core/repository/memory/BookMemoryRepository.java
  src/main/java/app/library/management/core/service/BookService.java
  src/main/java/app/library/management/core/service/response/dto/BookServiceResponse.java
  src/main/java/app/library/management/core/service/response/dto/status/ResponseState.java
  src/main/java/app/library/management/core/service/response/dto/status/Stage.java
  src/main/java/app/library/management/infra/console/Console.java
  src/main/java/app/library/management/infra/console/Input.java
  src/main/java/app/library/management/infra/console/Output.java
  src/main/java/app/library/management/infra/mode/ExecutionMode.java
  src/main/java/app/library/management/infra/port/Request.java
  src/main/java/app/library/management/infra/port/Response.java
  src/main/java/app/library/management/infra/port/dto/request/BookRequestDto.java
  src/main/java/app/library/management/infra/port/dto/response/BookResponseDto.java
  src/main/resources/application.properties
  src/test/java/app/library/management/core/domain/BookTest.java
  src/test/java/app/library/management/core/domain/util/BookStatusManagerTest.java
  src/test/java/app/library/management/core/repository/file/FileStorageAdaptorTest.java
  src/test/java/app/library/management/core/repository/file/FileStorageTest.java
  src/test/java/app/library/management/core/repository/memory/BookMemoryRepositoryTest.java
  src/test/java/app/library/management/core/service/BookServiceFileConcurrencyTest.java
  src/test/java/app/library/management/core/service/BookServiceMemoryConcurrencyTest.java
  src/test/java/app/library/management/core/service/BookServiceTest.java
Labels: Team-R, 🔥 매운맛

#19 [5기 - 조은비] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/library/Application.java
  src/main/java/com/programmers/library/constants/MessageConstants.java
  src/main/java/com/programmers/library/controller/MenuController.java
  src/main/java/com/programmers/library/controller/ModeConfigController.java
  src/main/java/com/programmers/library/dto/AddBookRequestDto.java
  src/main/java/com/programmers/library/dto/BorrowBookRequestDto.java
  src/main/java/com/programmers/library/dto/DeleteBookRequestDto.java
  src/main/java/com/programmers/library/dto/FindBookRequestDto.java
  src/main/java/com/programmers/library/dto/LostBookRequestDto.java
  src/main/java/com/programmers/library/dto/ReturnBookRequestDto.java
  src/main/java/com/programmers/library/entity/Book.java
  src/main/java/com/programmers/library/entity/BookStateType.java
  src/main/java/com/programmers/library/entity/state/AvailableState.java
  src/main/java/com/programmers/library/entity/state/BorrowedState.java
  src/main/java/com/programmers/library/entity/state/LostState.java
  src/main/java/com/programmers/library/entity/state/OrganizingState.java
  src/main/java/com/programmers/library/entity/state/State.java
  src/main/java/com/programmers/library/enums/Menu.java
  src/main/java/com/programmers/library/enums/Mode.java
  src/main/java/com/programmers/library/exception/BookException.java
  src/main/java/com/programmers/library/exception/ErrorCode.java
  src/main/java/com/programmers/library/io/ConsoleInput.java
  src/main/java/com/programmers/library/io/ConsoleOutput.java
  src/main/java/com/programmers/library/io/Input.java
  src/main/java/com/programmers/library/io/Output.java
  src/main/java/com/programmers/library/repository/BookRepository.java
  src/main/java/com/programmers/library/repository/FileBookRepository.java
  src/main/java/com/programmers/library/repository/MemoryBookRepository.java
  src/main/java/com/programmers/library/service/LibarayManagerService.java
  src/main/java/com/programmers/library/service/LibraryManagerServiceImpl.java
  src/main/java/com/programmers/library/util/FileReadBookDto.java
  src/main/java/com/programmers/library/util/FileUtils.java
  src/main/java/com/programmers/library/util/FileWriteBookDto.java
  src/main/java/com/programmers/library/util/IdGenerator.java
  src/main/resources/data.json
  src/test/java/com/programmers/library/dto/AddBookRequestDtoTest.java
  src/test/java/com/programmers/library/dto/BorrowBookRequestDtoTest.java
  src/test/java/com/programmers/library/dto/DeleteBookRequestDtoTest.java
  src/test/java/com/programmers/library/dto/FindBookRequestDtoTest.java
  src/test/java/com/programmers/library/dto/LostBookRequestDtoTest.java
  src/test/java/com/programmers/library/dto/MenuTest.java
  src/test/java/com/programmers/library/dto/ModeTest.java
  src/test/java/com/programmers/library/dto/ReturnBookRequestDtoTest.java
  src/test/java/com/programmers/library/entity/BookFixture.java
  src/test/java/com/programmers/library/entity/BookTest.java
  src/test/java/com/programmers/library/entity/state/AvailableStateTest.java
  src/test/java/com/programmers/library/entity/state/BorrowedStateTest.java
  src/test/java/com/programmers/library/entity/state/LostStateTest.java
  src/test/java/com/programmers/library/entity/state/OrganizingStateTest.java
  src/test/java/com/programmers/library/repository/FileBookRepositoryTest.java
  src/test/java/com/programmers/library/repository/MemoryBookRepositoryTest.java
  src/test/java/com/programmers/library/service/LibraryManagerServiceImplTest.java
  src/test/resources/data.json
Labels: 🔥 매운맛, Team-Dozzi

#12 [5기 - 김강훈] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  repository.csv
  setting.gradle
  src/main/java/Main.java
  src/main/java/client/Client.java
  src/main/java/client/ConsoleManager.java
  src/main/java/client/ExHandler.java
  src/main/java/client/Function.java
  src/main/java/domain/BackGround.java
  src/main/java/domain/Book.java
  src/main/java/domain/Status.java
  src/main/java/repository/FileRepository.java
  src/main/java/repository/Repository.java
  src/main/java/repository/TestRepository.java
  src/main/java/service/Service.java
  src/test/java/domain/BookTest.java
  src/test/java/repository/TestRepositoryTest.java
  src/test/java/service/ServiceTest.java
Labels: Team-Marco, 🔥 매운맛

#10 [5기 김대휘] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/Main.java
  src/main/java/com/programmers/common/ErrorMessages.java
  src/main/java/com/programmers/common/InfoMessages.java
  src/main/java/com/programmers/common/PromptMessages.java
  src/main/java/com/programmers/domain/Book.java
  src/main/java/com/programmers/domain/BookState.java
  src/main/java/com/programmers/provider/BookIdProvider.java
  src/main/java/com/programmers/repository/BookRepository.java
  src/main/java/com/programmers/repository/FileBookRepository.java
  src/main/java/com/programmers/repository/MemBookRepository.java
  src/main/java/com/programmers/service/BookService.java
  src/main/java/com/programmers/view/ConsoleUI.java
  src/main/resources/data.csv
  src/test/java/com/programmers/service/BookServiceTest.java
Labels: Team-Marco, 🔥 매운맛

#8 [5기 - 박유진] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/example/Console.java
  src/main/java/org/example/Main.java
  src/main/java/org/example/Mode.java
  src/main/java/org/example/domain/Book.java
  src/main/java/org/example/domain/BookRepository.java
  src/main/java/org/example/domain/BookState.java
  src/main/java/org/example/service/BookService.java
  src/main/java/org/example/service/FileService.java
  src/main/java/org/example/service/UpdateTask.java
  src/main/resources/book.csv
  src/test/java/org/example/domain/BookRepositoryTest.java
  src/test/java/org/example/service/BookServiceTest.java
Labels: Team-Marco, 🔥 매운맛

#6 [5기 - 김남규] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  csv/csvFile
  csv/csvTestFile
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/App.java
  src/main/java/domain/Book.java
  src/main/java/domain/BookCondition.java
  src/main/java/exception/InputFormatException.java
  src/main/java/exception/LoadException.java
  src/main/java/exception/SaveException.java
  src/main/java/io/Console.java
  src/main/java/repository/GeneralRepository.java
  src/main/java/repository/Repository.java
  src/main/java/repository/TestRepository.java
  src/main/java/service/Service.java
  src/main/java/service/TotalService.java
  src/main/java/view/MessagePrinter.java
  src/test/java/io/ConsoleTest.java
  src/test/java/repository/GeneralRepositoryTest.java
Labels: Team-Marco, 🔥 매운맛

#2 [5기 임수진] 1~2주차 과제 도서관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Main.java
  src/main/java/domain/Book.java
  src/main/java/domain/BookState.java
  src/main/java/domain/ConsolePrint.java
  src/main/java/domain/ModeType.java
  src/main/java/exception/FileReadException.java
  src/main/java/exception/FileWriteException.java
  src/main/java/exception/NotAppropriateScopeException.java
  src/main/java/exception/ThreadInterruptException.java
  src/main/java/message/ExecuteMessage.java
  src/main/java/message/QuestionMessage.java
  src/main/java/message/SelectMessage.java
  src/main/java/repository/FileRepository.java
  src/main/java/repository/MemoryRepository.java
  src/main/java/repository/Repository.java
  src/main/java/service/Mode.java
  src/main/java/service/Service.java
  src/main/java/thread/FileChangeStateThread.java
  src/main/java/thread/MemoryChangeStateThread.java
  src/main/java/view/Reader.java
  src/main/java/view/SelectMenu.java
  src/main/java/view/SelectMode.java
  src/main/resources/library.csv
  src/test/java/repository/FileRepositoryTest.java
  src/test/java/repository/MemoryRepositoryTest.java
  src/test/java/service/ServiceTest.java
Labels: Team-Marco, 🔥 매운맛

#34 [5기 - 박주한] 1~2주차 과제: 도서 관리 어플리케이션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/libraryManagement/DTO/BookRequestDTO.java
  src/main/java/com/libraryManagement/DTO/BookResponseDTO.java
  src/main/java/com/libraryManagement/LibraryManagementApplication.java
  src/main/java/com/libraryManagement/controller/BookController.java
  src/main/java/com/libraryManagement/domain/Book.java
  src/main/java/com/libraryManagement/domain/BookStatus.java
  src/main/java/com/libraryManagement/exception/ExceptionMessage.java
  src/main/java/com/libraryManagement/io/BookIO.java
  src/main/java/com/libraryManagement/io/BookMenu.java
  src/main/java/com/libraryManagement/io/ModeMenu.java
  src/main/java/com/libraryManagement/repository/FileRepository.java
  src/main/java/com/libraryManagement/repository/MemoryRepository.java
  src/main/java/com/libraryManagement/repository/Repository.java
  src/main/java/com/libraryManagement/service/BookService.java
  src/main/java/com/libraryManagement/util/AppConfig.java
  src/main/java/com/libraryManagement/util/MyScheduler.java
  src/main/resources/application.properties
  src/main/resources/static/books.json
  src/test/java/com/libraryManagement/LibraryManagementApplicationTests.java
  src/test/java/com/libraryManagement/repository/MemoryRepositoryTest.java
  src/test/java/com/libraryManagement/service/BookServiceTest.java
Labels: 🔥 매운맛, Team-Dozzi
